default_platform(:android)

platform :android do

  desc "Build android aab"
  lane :build_aab do
    begin
      # get the version of from google console which is in production  (note: this also return inreview app version)
      version = google_play_track_version_codes(track: 'production')[0].to_i
      # increament version code
      version = version +1
      # build script for flutter
      sh "/fastlane-files/flutter_build.sh #{version}"
    rescue => exception
      on_error(exception)
    end
  end

  desc "Deploy (Upload to play store)"
  # trigger this lane to upload app in internal app sharing
  # command: bundle exec fastlane internal_sharing 
  lane :internal_sharing do |options|
    begin
      applink= upload_to_play_store_internal_app_sharing(
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        )

      # send link of internal app sharing in slack channel
      slack_url = "https://hooks.slack.com/services/....."
      slack(
           message: "App Updated!",
           success: true,
           slack_url: slack_url,
           attachment_properties: { 
           fields: [{
            title: "app link",
            value: applink,
            short: false
            }]
          }
        )
      rescue => exception
        on_error(exception)
      end
    end

  desc "Deploy (Upload to play store)"
  #  we will upload to production by default
  lane :deploy_android do |options|
    begin
      upload_to_play_store(
        track: options[:production],
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_images: true,
        skip_upload_screenshots: true,
      )
      slack(
        message: "App sucessfully published in play store.",
        success: true,
        slack_url: "https://hooks.slack.com/services/...",
    )
    rescue => exception
      on_error(exception)
    end
  end


  def on_error(exception)
    slack(
        message: "App name !! thing goes wrong",
        success: false,
        slack_url: "https://hooks.slack.com/services/..",
        attachment_properties: {
            fields: [
                {
                    title: "Error message",
                    value: exception.to_s,
                    short: false
                }
            ]
        }
    )
  end

end