default_platform(:android)

platform :android do

  desc "Build android aab"
  lane :build_aab do
    # get the version of from google console which is in production  (note: this also return inreview app version)
    version = google_play_track_version_codes(track: 'production')[0].to_i
    # increament version code
    version = version +1
    # build script for flutter
    sh "/fastlane-files/flutter_build.sh #{version}"
  end

end